# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "model_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13model_service.proto\x12\x0cmodelservice"\x07\n\x05\x45mpty"\x1b\n\tModelList\x12\x0e\n\x06models\x18\x01 \x03(\t"@\n\x0cTrainRequest\x12\x12\n\nmodel_type\x18\x01 \x01(\t\x12\r\n\x01X\x18\x02 \x03(\x01\x42\x02\x10\x01\x12\r\n\x01y\x18\x03 \x03(\x05\x42\x02\x10\x01"2\n\rTrainResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t"1\n\x0ePredictRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\r\n\x01X\x18\x02 \x03(\x01\x42\x02\x10\x01"&\n\x0fPredictResponse\x12\x13\n\x0bpredictions\x18\x01 \x03(\x01"!\n\rDeleteRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa3\x02\n\x0cModelService\x12:\n\nListModels\x12\x13.modelservice.Empty\x1a\x17.modelservice.ModelList\x12\x45\n\nTrainModel\x12\x1a.modelservice.TrainRequest\x1a\x1b.modelservice.TrainResponse\x12\x46\n\x07Predict\x12\x1c.modelservice.PredictRequest\x1a\x1d.modelservice.PredictResponse\x12H\n\x0b\x44\x65leteModel\x12\x1b.modelservice.DeleteRequest\x1a\x1c.modelservice.DeleteResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "model_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_TRAINREQUEST"].fields_by_name["X"]._loaded_options = None
    _globals["_TRAINREQUEST"].fields_by_name["X"]._serialized_options = b"\020\001"
    _globals["_TRAINREQUEST"].fields_by_name["y"]._loaded_options = None
    _globals["_TRAINREQUEST"].fields_by_name["y"]._serialized_options = b"\020\001"
    _globals["_PREDICTREQUEST"].fields_by_name["X"]._loaded_options = None
    _globals["_PREDICTREQUEST"].fields_by_name["X"]._serialized_options = b"\020\001"
    _globals["_EMPTY"]._serialized_start = 37
    _globals["_EMPTY"]._serialized_end = 44
    _globals["_MODELLIST"]._serialized_start = 46
    _globals["_MODELLIST"]._serialized_end = 73
    _globals["_TRAINREQUEST"]._serialized_start = 75
    _globals["_TRAINREQUEST"]._serialized_end = 139
    _globals["_TRAINRESPONSE"]._serialized_start = 141
    _globals["_TRAINRESPONSE"]._serialized_end = 191
    _globals["_PREDICTREQUEST"]._serialized_start = 193
    _globals["_PREDICTREQUEST"]._serialized_end = 242
    _globals["_PREDICTRESPONSE"]._serialized_start = 244
    _globals["_PREDICTRESPONSE"]._serialized_end = 282
    _globals["_DELETEREQUEST"]._serialized_start = 284
    _globals["_DELETEREQUEST"]._serialized_end = 317
    _globals["_DELETERESPONSE"]._serialized_start = 319
    _globals["_DELETERESPONSE"]._serialized_end = 352
    _globals["_MODELSERVICE"]._serialized_start = 355
    _globals["_MODELSERVICE"]._serialized_end = 646
# @@protoc_insertion_point(module_scope)
